<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<div class="container">
	<div class="row">
		<h1 >Bienvenido</h1>
		<a class="btn btn-danger" href="<?php echo BASE_URL?>index/logout">Logout</a>
		<a class="btn btn-primary" href="<?php echo BASE_URL?>usuario/index">Lista de Usuario</a>
	</div>
	
	

<!--<?php print_r($_SESSION); ?> -->




 </div>